# Terraform

[[override]]
  name = "github.com/aws/aws-sdk-go"
  version = "=1.17.12"

[[override]]
  name = "github.com/gophercloud/gophercloud"
  revision = "bc37892e196848d7d56ba0db974ba1d7d5c43b2a"

[[override]]
  # last version without The Glue service which does not compile...
  name = "github.com/terraform-providers/terraform-provider-aws"
  version = "=1.23.0"

[[override]]
  name = "github.com/ugorji/go"
  version = "=1.1.1"

[[override]]
  name = "github.com/coreos/etcd"
  version = "3.3.12"

[[constraint]]
  name = "github.com/hashicorp/terraform"
  version = "=0.11.13"

# Packer

[[constraint]]
  name = "github.com/hashicorp/packer"
  version = "=1.3.5"